### ISSUE TITLE
run `mvn clean install` failed

### ISSUE THREAD

**Issue by hyzx86** [bonitasoft/bonita-web#308]
The address is not exists
`http://oauth.googlecode.com/svn/code/maven/org/bonitasoft/engine/bonita-engine/7.6.4-SNAPSHOT/maven-metadata.xml
`
Is this project dead?

PS D:\testCodes\bonita-web-master> mvn clean install
[INFO] Scanning for projects...
Downloading from oauth: http://oauth.googlecode.com/svn/code/maven/org/bonitasoft/engine/bonita-engine/7.6.4-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.bonitasoft.engine:bonita-engine:7.6.4-SNAPSHOT/maven-metadata.xml from/to oauth (http://oauth.googlecode.com/svn/code/maven/): Connect to oauth.googlecode.com:80 [oauth.googlecode.com/74.125.204.82] failed: Connection timed out: connect
Downloading from oauth: http://oauth.googlecode.com/svn/code/maven/org/bonitasoft/engine/bonita-engine/7.6.4-SNAPSHOT/bonita-engine-7.6.4-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not transfer artifact org.bonitasoft.engine:bonita-engine:pom:7.6.4-SNAPSHOT from/to oauth (http://oauth.googlecode.com/svn/code/maven/): Connect to oauth.googlecode.com:80 [oauth.googlecode.com/74.125.204.82] failed: Connection timed out: connect @ line 48, column 25
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.bonitasoft.console:bonita-console:7.6.4-SNAPSHOT (D:\testCodes\bonita-web-master\pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.bonitasoft.engine:bonita-engine:pom:7.6.4-SNAPSHOT from/to oauth (http://oauth.googlecode.com/svn/code/maven/): Connect to oauth.googlecode.com:80 [oauth.googlecode.com/74.125.204.82] failed: Connection timed out: connect @ line 48, column 25 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by tbouffard** [comment]
Hello
no, this project is not dead at all (see the latest commit available in the master branch 8b0a611c6f23cc45c07fdef9b12f572972623861 which is 12 days old)

First, if you try to build the master branch, you should see issue with version `7.7.4-SNAPSHOT` instead of `7.6.4-SNAPSHOT`
2nd, please use the Maven Wrapper as documented in the readme instead of any maven installation on your machine: we guarantee the build to work only with the wrapper (which set a specific maven version), not with other maven versions.

About your issue, this is because you have to install (locally or a Repository Manager) the corresponding SNAPSHOT version of the [bonita-engine](https://github.com/bonitasoft/bonita-engine) (see the Readme of this project to know how to build it) if you want to build the master branch. You won't have this issue if you want to buid a tag as the Engine componants of a tagged version are available on Maven Central.

**Comment by hyzx86** [comment]
Thanks for your help.
